# Generated by Django 6.1.1 on 2026-09-27 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier used in Redis keys and the connect URL.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('max_sessions', models.PositiveIntegerField(default=100, help_text='Hard ceiling on concurrent sessions for this org.', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_floor', models.PositiveIntegerField(default=0, help_text='Concurrent sessions this org can always reach, even when global capacity is exhausted. Must not exceed max_sessions.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive orgs are refused at connect time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, unique=True)),
                ('node_id', models.CharField(db_index=True, max_length=128)),
                ('client_id', models.CharField(blank=True, help_text='Caller-supplied end-user identifier, opaque to this layer.', max_length=128)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('client', 'Client disconnected'), ('node_lost', 'Node stopped heartbeating'), ('drained', 'Node drained for shutdown'), ('rejected', 'Refused at admission')], max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='connsessions.organization')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['organization', 'ended_at'], name='connsession_organiz_6f6c79_idx'), models.Index(fields=['node_id', 'ended_at'], name='connsession_node_id_246710_idx')],
            },
        ),
    ]
